"""Integration tests for the TLE clustering pipeline.

Exercises the full path from raw multi-provider TLE strings through
:func:`spectre.astro.tle_preprocessing.cluster_and_reduce_tle_cache` to a
reduced ``hrr_tle_cache``.

Tests use synthetic TLEs generated by the same helper used in the unit
tests so the checksums and column alignment are guaranteed correct.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Shared TLE builder (mirrors tests/unit/tle_clustering/conftest.py)
# ---------------------------------------------------------------------------

_EPOCH = "26091.50000000"


def _checksum(line: str) -> int:
    total = 0
    for ch in line[:-1]:
        if ch.isdigit():
            total += int(ch)
        elif ch == "-":
            total += 1
    return total % 10


def _make_tle_pair(norad: int, inc: float, raan: float, ecc: float) -> tuple[str, str]:
    n = f"{norad:05d}"
    ecc_str = f"{ecc:.7f}"[2:]
    l1_body = (
        f"1 {n}U 98067A   {_EPOCH}"
        f"  .00000000"
        f"  00000-0"
        f"  00000-0"
        f" 0  999"
    )
    l1 = l1_body + str(_checksum(l1_body + "0"))
    l2_body = (
        f"2 {n} "
        f"{inc:8.4f} "
        f"{raan:8.4f} "
        f"{ecc_str} "
        f"100.0000 "
        f"200.0000 "
        f"15.5432109800001"
    )
    l2 = l2_body + str(_checksum(l2_body + "0"))
    return l1, l2


def _tle_string(norad: int, inc: float, raan: float, ecc: float) -> str:
    l1, l2 = _make_tle_pair(norad, inc, raan, ecc)
    return f"{l1}\n{l2}"


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

_TLES_A = [
    # NORAD 25544 — five tight TLEs, all within default tolerances → 1 cluster
    _tle_string(25544, 51.6400, 247.1234, 0.0001234),
    _tle_string(25544, 51.6405, 247.1244, 0.0001239),
    _tle_string(25544, 51.6398, 247.1220, 0.0001230),
    _tle_string(25544, 51.6403, 247.1250, 0.0001237),
    _tle_string(25544, 51.6401, 247.1240, 0.0001236),
]

_TLES_B = [
    # NORAD 43013 — two tight TLEs → 1 cluster
    _tle_string(43013, 98.2000, 100.0000, 0.0008000),
    _tle_string(43013, 98.2002, 100.0010, 0.0007999),
]

_TLES_C = [
    # NORAD 99001 — two TLEs spread far apart → 2 noise items (no cluster forms)
    _tle_string(99001, 28.5000, 45.0000, 0.0003000),
    _tle_string(99001, 51.6000, 247.0000, 0.0001000),
]

_EXISTING_CACHE = {
    "25544": _tle_string(25544, 51.6400, 247.1234, 0.0001234),
    "43013": _tle_string(43013, 98.2000, 100.0000, 0.0008000),
    "99001": _tle_string(99001, 28.5000, 45.0000, 0.0003000),
    "77777": _tle_string(12345, 35.0000, 55.0000, 0.0002000),  # not in multiset
}

_MULTISET = {
    "25544": _TLES_A,
    "43013": _TLES_B,
    "99001": _TLES_C,
}

_CONFIG = {
    "inclination_tolerance_deg": 0.01,
    "raan_tolerance_deg": 0.05,
    "eccentricity_tolerance": 1e-4,
    "dbscan_min_samples": 2,
    "fetch_window_hours": 24,
}


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestClusterAndReduceTleCache:

    def test_reduced_cache_has_fewer_entries_than_tles_in(self):
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        reduced, summary = cluster_and_reduce_tle_cache(_MULTISET, _EXISTING_CACHE, _CONFIG)

        # Total TLEs submitted: 5 + 2 + 2 = 9; reduced to at most 3 representatives
        assert summary.total_tles_in == 9
        assert summary.total_representatives_out <= summary.total_tles_in

    def test_reduced_cache_preserves_unchanged_keys(self):
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        reduced, _ = cluster_and_reduce_tle_cache(_MULTISET, _EXISTING_CACHE, _CONFIG)

        # satno 77777 was not in multiset — existing_cache value should be passed through
        # (caller does state.hrr_tle_cache.update(reduced), so 77777 stays in the original)
        # The reduced cache only touches satnos that were clustered; we verify 25544 is present.
        assert "25544" in reduced

    def test_tight_cluster_reduces_to_one_representative(self):
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        reduced, summary = cluster_and_reduce_tle_cache(
            {"25544": _TLES_A}, {"25544": _TLES_A[0]}, _CONFIG
        )

        obj = next(o for o in summary.objects if o.satno == "25544")
        assert obj.clusters_found == 1
        assert obj.representatives_out == 1
        assert reduced["25544"].count("\n") == 1  # two lines joined by \n

    def test_all_representatives_are_sgp4_parseable(self):
        from sgp4.api import Satrec

        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        reduced, _ = cluster_and_reduce_tle_cache(_MULTISET, _EXISTING_CACHE, _CONFIG)

        for key, tle_str in reduced.items():
            lines = tle_str.strip().splitlines()
            assert len(lines) == 2, f"Expected 2 TLE lines for {key}, got {len(lines)}"
            sat = Satrec.twoline2rv(lines[0], lines[1])
            assert sat.error == 0, f"sgp4 parse error for {key}: error code {sat.error}"

    def test_summary_stats_are_consistent(self):
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        _, summary = cluster_and_reduce_tle_cache(_MULTISET, _EXISTING_CACHE, _CONFIG)

        # Aggregate counts match per-object breakdown
        assert summary.total_tles_in == sum(o.tles_in for o in summary.objects if not o.skipped)
        assert summary.total_noise == sum(o.noise_count for o in summary.objects if not o.skipped)
        assert summary.objects_clustered + summary.objects_skipped == len(summary.objects)

    def test_single_provider_object_is_skipped_not_errored(self):
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        single_tle = _tle_string(12345, 35.0, 55.0, 0.0002)
        reduced, summary = cluster_and_reduce_tle_cache(
            {"12345": [single_tle]},
            {"12345": single_tle},
            _CONFIG,
        )

        obj = summary.objects[0]
        assert obj.skipped is True
        assert summary.objects_skipped == 1
        assert summary.objects_clustered == 0

    def test_empty_multiset_returns_empty_reduced_and_zero_stats(self):
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        reduced, summary = cluster_and_reduce_tle_cache({}, _EXISTING_CACHE, _CONFIG)

        assert reduced == {}
        assert summary.total_tles_in == 0
        assert summary.objects_clustered == 0

    def test_satnos_absent_from_multiset_unchanged_in_existing_cache(self):
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        reduced, _ = cluster_and_reduce_tle_cache(
            {"25544": _TLES_A},
            _EXISTING_CACHE,
            _CONFIG,
        )

        # 43013 not in multiset — reduced cache should not contain it
        assert "43013" not in reduced
        # But 25544 should be updated
        assert "25544" in reduced

    def test_overall_reduction_pct_bounded(self):
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        _, summary = cluster_and_reduce_tle_cache(_MULTISET, _EXISTING_CACHE, _CONFIG)

        assert 0.0 <= summary.overall_reduction_pct <= 100.0

    def test_no_indexed_keys_written_to_reduced_cache(self):
        """Multi-cluster objects must NOT produce satno_0 / satno_1 keys.

        The sweep pipeline only looks up plain satno keys.  Indexed keys
        would be invisible to the sweep and accumulate as stale cache entries.
        """
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        reduced, _ = cluster_and_reduce_tle_cache(_MULTISET, _EXISTING_CACHE, _CONFIG)

        for key in reduced:
            # No key should contain an underscore followed by a digit.
            assert not (key[-2] == "_" and key[-1].isdigit()), (
                f"Indexed cache key '{key}' found — multi-cluster objects "
                "must write exactly one entry under the plain satno."
            )

    def test_multi_cluster_object_flags_elevated_uncertainty(self):
        """When DBSCAN finds >1 cluster, multi_cluster=True must be set on the summary object."""
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        # Build two clearly separate clusters for the same NORAD by using
        # element values far apart (different inclinations).
        norad = 55555
        cluster_a = [
            _tle_string(norad, 28.5, 45.0, 0.0003),
            _tle_string(norad, 28.5, 45.1, 0.0003),
        ]
        cluster_b = [
            _tle_string(norad, 51.6, 247.0, 0.0001),
            _tle_string(norad, 51.6, 247.1, 0.0001),
        ]
        all_tles = cluster_a + cluster_b
        existing = {str(norad): all_tles[0]}

        reduced, summary = cluster_and_reduce_tle_cache(
            {str(norad): all_tles}, existing, _CONFIG
        )

        obj = next((o for o in summary.objects if o.satno == str(norad)), None)
        if obj and obj.clusters_found > 1:
            assert obj.multi_cluster is True
        # Regardless, exactly one TLE written per satno.
        if str(norad) in reduced:
            assert reduced[str(norad)].count("\n") == 1

    def test_all_noise_uses_fallback_not_error(self):
        """When all TLEs are noise, the fallback cached TLE must be retained."""
        from spectre.astro.tle_preprocessing import cluster_and_reduce_tle_cache

        # Two TLEs far enough apart to not cluster together but using only 2 TLEs
        # with min_samples=2: each TLE is its own neighbourhood of size 1 → noise.
        norad = 77777
        lone_a = _tle_string(norad, 28.5, 45.0, 0.0003)
        lone_b = _tle_string(norad, 99.9, 200.0, 0.005)
        fallback_tle = _tle_string(norad, 28.5, 45.0, 0.0003)
        existing = {str(norad): fallback_tle}

        reduced, summary = cluster_and_reduce_tle_cache(
            {str(norad): [lone_a, lone_b]}, existing, _CONFIG
        )

        obj = next((o for o in summary.objects if o.satno == str(norad)), None)
        # The object should be accounted for — either clustered or fallback.
        assert obj is not None
        # If all noise, fallback should be used and reduced cache should have the entry.
        if obj and obj.noise_count == 2:
            assert obj.fallback is True
            assert str(norad) in reduced
            assert reduced[str(norad)] == fallback_tle

    def test_from_constants_propagates_dbscan_eps_and_metric(self):
        """ClusteringConfig.from_constants must forward dbscan_eps and dbscan_metric."""
        from tle_clustering.config import ClusteringConfig

        cfg = ClusteringConfig.from_constants({
            "inclination_tolerance_deg": 0.02,
            "raan_tolerance_deg": 0.10,
            "eccentricity_tolerance": 2e-4,
            "dbscan_eps": 1.5,
            "dbscan_min_samples": 3,
            "dbscan_metric": "euclidean",
        })
        assert cfg.dbscan_eps == 1.5
        assert cfg.dbscan_metric == "euclidean"
        assert cfg.dbscan_min_samples == 3
        assert cfg.inclination_tolerance_deg == 0.02


class TestClusteringSummaryDataclasses:

    def test_object_summary_fields(self):
        from spectre.astro.tle_preprocessing import ObjectClusteringSummary

        obj = ObjectClusteringSummary(
            satno="25544", tles_in=5, clusters_found=1,
            representatives_out=1, noise_count=0, reduction_pct=80.0,
        )
        assert obj.satno == "25544"
        assert obj.skipped is False  # default
        assert obj.multi_cluster is False
        assert obj.fallback is False

    def test_clustering_summary_defaults(self):
        from spectre.astro.tle_preprocessing import ClusteringSummary

        cs = ClusteringSummary()
        assert cs.objects == []
        assert cs.total_tles_in == 0
        assert cs.overall_reduction_pct == 0.0
        assert cs.objects_multi_cluster == 0
        assert cs.objects_fallback == 0
