#!/bin/sh
# Build the Bluestaq App Store upload package for SPECTRE.
#
# The package is a FLAT, TESTABLE SOURCE TREE:
#   * flat        the Dockerfile sits at the zip root, with no wrapping folder,
#                 so template detection finds it and the generated build uses
#                 the root as its context. A nested Dockerfile fails with
#                 "context must be a directory".
#   * testable    tests, their config and the lockfile all ship, so the platform
#                 can run the suite against the zip root. Under docker-only it
#                 will not, but a stripped runtime bundle cannot be reviewed and
#                 could not switch to the python template later.
#
# The packaging allowlist and .dockerignore are SEPARATE contracts: this shapes
# the upload the platform inspects, .dockerignore shapes the image it runs.
#
# POSIX sh only: the platform runs build steps under a minimal shell.
#
# Usage:
#   scripts/package-appstore.sh [output-dir]                  python template
#   scripts/package-appstore.sh [output-dir] --docker-only    docker-only template
#
# TEMPLATE SELECTION IS DECIDED BY WHAT IS IN THE PACKAGE, NOT BY A SETTING.
# The platform detects Python from a recognised manifest at the package root.
# Evidence: the first upload had pyproject.toml and no requirements.txt, and a
# Dependencies stage still ran and failed; a docker-only app has no such stage.
# So docker-only requires that NO recognised manifest ships: no pyproject.toml
# and no requirements.txt. requirements.lock is not a recognised name, so
# dependency pinning survives, and Dockerfile.docker-only runs the app via
# `python -m` instead of installing it.

set -eu

OUT_DIR="${1:-dist}"
MODE="python"
case "${2:-}" in
    --docker-only) MODE="docker-only" ;;
    "") ;;
    *) echo "FAIL: unknown option ${2}"; exit 1 ;;
esac
VERSION=$(sed -n 's/^__version__ = "\(.*\)"$/\1/p' spectre/__init__.py)
[ -n "$VERSION" ] || { echo "FAIL: could not read __version__ from spectre/__init__.py"; exit 1; }

STAGE=$(mktemp -d)
if [ "$MODE" = "docker-only" ]; then
    PKG_NAME="spectre-${VERSION}-appstore-docker-only"
else
    PKG_NAME="spectre-${VERSION}-appstore"
fi
ZIP_PATH="${OUT_DIR}/${PKG_NAME}.zip"

cleanup() { rm -rf "$STAGE"; }
trap cleanup EXIT INT TERM

echo "Packaging SPECTRE ${VERSION} for the App Store (${MODE} template)"

# ── Allowlist ─────────────────────────────────────────────────────────────────
# Everything the platform needs to detect the template, build the image, run the
# suite, and review the submission. Nothing else.
PATHS="
Dockerfile
.dockerignore
requirements.lock
requirements.txt
pyproject.toml
sonar-project.properties
README.md
CHANGELOG.md
SECURITY.md
READINESS.md
CODEOWNERS
.env.example
.gitignore
.pre-commit-config.yaml
spectre
tests
tle_clustering
scripts
.github
"

if [ "$MODE" = "docker-only" ]; then
    # A recognised manifest anywhere at the root would flip the template back to
    # python, so pyproject.toml, requirements.txt and the Sonar config all go.
    # tests/ goes with them: without pyproject.toml there is no pytest config,
    # so shipping an unrunnable suite would mislead a reviewer.
    PATHS=$(printf '%s\n' $PATHS | grep -vxE 'pyproject.toml|requirements.txt|sonar-project.properties|tests|tle_clustering|.github|.pre-commit-config.yaml')
fi

for p in $PATHS; do
    [ -e "$p" ] || { echo "FAIL: allowlisted path missing: $p"; exit 1; }
    mkdir -p "$STAGE/$(dirname "$p")"
    cp -R "$p" "$STAGE/$(dirname "$p")/"
done

# ── Denylist ──────────────────────────────────────────────────────────────────
# Removed after the copy so a nested match cannot survive. Each has a reason.
#   __pycache__, *.pyc      build cruft
#   .env and variants       real secrets must never travel in an upload
#   coverage output, .db    generated locally, regenerated by the pipeline
#   data/, logs/            runtime state; the container uses the storage add-on
#   dist/, *.zip            no package inside a package
#   docs/                   document generators and reference material. Not
#                           imported by the app, not needed to build or test,
#                           and its .py generators are analysed by the platform
#                           scanner as if they were application code, which
#                           lowers the coverage ratio and raises smells against
#                           files that never ship
find "$STAGE" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" \( -name '*.pyc' -o -name '*.pyo' -o -name '*.db' -o -name '*.zip' \) -delete 2>/dev/null || true
find "$STAGE" \( -name '.env' -o -name '.env.*' \) ! -name '.env.example' -delete 2>/dev/null || true
find "$STAGE" \( -name '.coverage' -o -name 'coverage.xml' \) -delete 2>/dev/null || true
rm -rf "$STAGE/docs" "$STAGE/.git" "$STAGE/.venv" "$STAGE/venv" "$STAGE/dist" "$STAGE/htmlcov" \
       "$STAGE/coverage" "$STAGE/.pytest_cache" "$STAGE/.mypy_cache" "$STAGE/.ruff_cache" \
       "$STAGE/data" "$STAGE/logs" "$STAGE/docs/openapi.json"

if [ "$MODE" = "docker-only" ]; then
    [ -f Dockerfile.docker-only ] || { echo "FAIL: Dockerfile.docker-only is missing"; exit 1; }
    cp Dockerfile.docker-only "$STAGE/Dockerfile"
fi

# ── Fail-closed checks on the staged tree ─────────────────────────────────────
[ -f "$STAGE/Dockerfile" ] || { echo "FAIL: Dockerfile must be at the package root"; exit 1; }

if [ "$MODE" = "python" ]; then
    # The Dependencies stage installs from requirements.txt. Without it the
    # stage fails before anything else runs.
    if [ ! -f "$STAGE/requirements.txt" ]; then
        echo "FAIL: no requirements.txt at the package root."
        echo "      The platform's dependency install has nothing to read and will fail."
        exit 1
    fi
else
    # Any recognised manifest would flip detection back to the python template.
    for manifest in pyproject.toml requirements.txt setup.py setup.cfg Pipfile poetry.lock; do
        if [ -f "$STAGE/$manifest" ]; then
            echo "FAIL: $manifest at the root would select the python template, not docker-only."
            exit 1
        fi
    done
fi

LEAKS=$(find "$STAGE" \( -name '.env' -o -name '*.pem' -o -name '*.key' -o -name 'id_rsa*' \) 2>/dev/null | grep -v '\.env\.example' || true)
[ -z "$LEAKS" ] || { echo "FAIL: credential-shaped files in the package:"; echo "$LEAKS"; exit 1; }

if grep -rIlE '^SECRET_KEY=.+|^SPECTRE_ADMIN_PASS=.+' "$STAGE" 2>/dev/null | head -1 | grep -q .; then
    echo "FAIL: a populated secret value is present in the package"
    exit 1
fi

# ── Build ─────────────────────────────────────────────────────────────────────
mkdir -p "$OUT_DIR"
rm -f "$ZIP_PATH"
# -X drops extra file attributes so the archive is reproducible across machines.
( cd "$STAGE" && zip -q -r -X "$OLDPWD/$ZIP_PATH" . )

# ── Integrity record ──────────────────────────────────────────────────────────
SHA=$(sha256sum "$ZIP_PATH" | cut -d' ' -f1)
SIZE=$(du -h "$ZIP_PATH" | cut -f1)
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > "${OUT_DIR}/${PKG_NAME}.sha256" <<EOF
$SHA  ${PKG_NAME}.zip
EOF

echo
echo "  package   $ZIP_PATH"
echo "  version   $VERSION"
echo "  commit    $COMMIT"
echo "  size      $SIZE"
echo "  sha256    $SHA"
echo "  files     $(unzip -l "$ZIP_PATH" | tail -1 | awk '{print $2}')"
echo
echo "Verify the contents with:  unzip -l $ZIP_PATH"
