#!/bin/sh
# Build the Bluestaq App Store upload package for SPECTRE.
#
# The package is a FLAT, TESTABLE SOURCE TREE:
#   * flat        the Dockerfile sits at the zip root, with no wrapping folder,
#                 so template detection finds it and the generated build uses
#                 the root as its context. A nested Dockerfile fails with
#                 "context must be a directory".
#   * testable    tests, their config and the lockfile all ship, so the platform
#                 can run the suite against the zip root. Under docker-only it
#                 will not, but a stripped runtime bundle cannot be reviewed and
#                 could not switch to the python template later.
#
# The packaging allowlist and .dockerignore are SEPARATE contracts: this shapes
# the upload the platform inspects, .dockerignore shapes the image it runs.
#
# POSIX sh only: the platform runs build steps under a minimal shell.
#
# Usage:  scripts/package-appstore.sh [output-directory]     (default: dist)

set -eu

OUT_DIR="${1:-dist}"
VERSION=$(sed -n 's/^__version__ = "\(.*\)"$/\1/p' spectre/__init__.py)
[ -n "$VERSION" ] || { echo "FAIL: could not read __version__ from spectre/__init__.py"; exit 1; }

STAGE=$(mktemp -d)
PKG_NAME="spectre-${VERSION}-appstore"
ZIP_PATH="${OUT_DIR}/${PKG_NAME}.zip"

cleanup() { rm -rf "$STAGE"; }
trap cleanup EXIT INT TERM

echo "Packaging SPECTRE ${VERSION} for the App Store (docker-only template)"

# ── Allowlist ─────────────────────────────────────────────────────────────────
# Everything the platform needs to detect the template, build the image, run the
# suite, and review the submission. Nothing else.
PATHS="
Dockerfile
.dockerignore
requirements.lock
requirements.txt
pyproject.toml
sonar-project.properties
README.md
CHANGELOG.md
SECURITY.md
READINESS.md
CODEOWNERS
.env.example
.gitignore
.pre-commit-config.yaml
spectre
tests
tle_clustering
scripts
.github
docs
"

for p in $PATHS; do
    [ -e "$p" ] || { echo "FAIL: allowlisted path missing: $p"; exit 1; }
    mkdir -p "$STAGE/$(dirname "$p")"
    cp -R "$p" "$STAGE/$(dirname "$p")/"
done

# ── Denylist ──────────────────────────────────────────────────────────────────
# Removed after the copy so a nested match cannot survive. Each has a reason.
#   __pycache__, *.pyc      build cruft
#   .env and variants       real secrets must never travel in an upload
#   coverage output, .db    generated locally, regenerated by the pipeline
#   data/, logs/            runtime state; the container uses the storage add-on
#   dist/, *.zip            no package inside a package
#   docs/openapi.json       a 12 MB generated schema dump, not needed to build,
#                           test or review, and it slows every upload cycle
find "$STAGE" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" \( -name '*.pyc' -o -name '*.pyo' -o -name '*.db' -o -name '*.zip' \) -delete 2>/dev/null || true
find "$STAGE" \( -name '.env' -o -name '.env.*' \) ! -name '.env.example' -delete 2>/dev/null || true
find "$STAGE" \( -name '.coverage' -o -name 'coverage.xml' \) -delete 2>/dev/null || true
rm -rf "$STAGE/.git" "$STAGE/.venv" "$STAGE/venv" "$STAGE/dist" "$STAGE/htmlcov" \
       "$STAGE/coverage" "$STAGE/.pytest_cache" "$STAGE/.mypy_cache" "$STAGE/.ruff_cache" \
       "$STAGE/data" "$STAGE/logs" "$STAGE/docs/openapi.json"

# ── Fail-closed checks on the staged tree ─────────────────────────────────────
[ -f "$STAGE/Dockerfile" ] || { echo "FAIL: Dockerfile must be at the package root"; exit 1; }

# The platform's Dependencies stage installs from requirements.txt. Without it
# the stage fails before anything else runs. Its presence selects the python
# template, which is deliberate; the Dockerfile still drives the image build.
if [ ! -f "$STAGE/requirements.txt" ]; then
    echo "FAIL: no requirements.txt at the package root."
    echo "      The platform's dependency install has nothing to read and will fail."
    exit 1
fi

LEAKS=$(find "$STAGE" \( -name '.env' -o -name '*.pem' -o -name '*.key' -o -name 'id_rsa*' \) 2>/dev/null | grep -v '\.env\.example' || true)
[ -z "$LEAKS" ] || { echo "FAIL: credential-shaped files in the package:"; echo "$LEAKS"; exit 1; }

if grep -rIlE '^SECRET_KEY=.+|^SPECTRE_ADMIN_PASS=.+' "$STAGE" 2>/dev/null | head -1 | grep -q .; then
    echo "FAIL: a populated secret value is present in the package"
    exit 1
fi

# ── Build ─────────────────────────────────────────────────────────────────────
mkdir -p "$OUT_DIR"
rm -f "$ZIP_PATH"
# -X drops extra file attributes so the archive is reproducible across machines.
( cd "$STAGE" && zip -q -r -X "$OLDPWD/$ZIP_PATH" . )

# ── Integrity record ──────────────────────────────────────────────────────────
SHA=$(sha256sum "$ZIP_PATH" | cut -d' ' -f1)
SIZE=$(du -h "$ZIP_PATH" | cut -f1)
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > "${OUT_DIR}/${PKG_NAME}.sha256" <<EOF
$SHA  ${PKG_NAME}.zip
EOF

echo
echo "  package   $ZIP_PATH"
echo "  version   $VERSION"
echo "  commit    $COMMIT"
echo "  size      $SIZE"
echo "  sha256    $SHA"
echo "  files     $(unzip -l "$ZIP_PATH" | tail -1 | awk '{print $2}')"
echo
echo "Verify the contents with:  unzip -l $ZIP_PATH"
